/* Autogenerated by png2wx.pl on Thu Feb 22 17:18:10 2024 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#   include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_TileChart;
extern wxBitmap* _img_TileChart_pi;

#endif /* ICONS_H */
