/* Autogenerated by png2wx.pl on Thu Feb 22 17:18:10 2024 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#   include <wx/wx.h>
#endif

#include <wx/filename.h>
#include <wx/mstream.h>

extern void initialize_images(void);

extern wxBitmap *_img_TileChart;
extern wxBitmap* _img_TileChart_pi;

#ifdef PLUGIN_USE_SVG
extern wxString _svg_TileChart;
extern wxString _svg_TileChart_rollover;
extern wxString _svg_TileChart_toggled;
#endif

#endif /* ICONS_H */
